rootPageId: 1
base: '/'
baseVariants:
#  -
#    base: 'http://all-power.ru'
#    condition: 'getenv("HOST_ENV") == "serverlive"'
  -
    base: 'http://all-power.localhost'
    condition: 'getenv("HOST_ENV") == "localdev"'
  -
    base: 'http://cj24618.tmweb.ru/'
    condition: 'getenv("HOST_ENV") == "serverdev"'

languages:
  -
    title: Russian
    enabled: true
    languageId: '0'
    base: /
    typo3Language: ru
    locale: ru_RU.UTF-8
    iso-639-1: ru
    navigationTitle: Russian
    hreflang: ru-Ru
    direction: ltr
    fallbackType: fallback
    fallbacks: '0'
    flag: ru

routes: {  }